apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    layer: frontend
    environment: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Example annotation for AWS NLB
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # Example annotation for Azure internal LB
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      nodePort: 30000
      port: 80
      targetPort: 80
  externalTrafficPolicy: Cluster  # Keeps client source IP
  sessionAffinity: None  # Ensures that sessions are not sticky