---
# Define a Service named "phpfpm"
kind: Service
apiVersion: v1
metadata:
  name: phpfpm
  labels:
    app: phpfpm
    layer: backend
spec:
  # Set the service type to ClusterIP
  type: ClusterIP
  # Select the pods with label "app: phpfpm"
  selector:
    app: phpfpm
  # Define a port mapping
  ports:
    - port: 9000
      targetPort: 9000